# Generated by Django 4.1.12 on 2023-11-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=255)),
                ('sound_volumn', models.DecimalField(decimal_places=1, max_digits=3)),
                ('notification', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('all_time_money', models.IntegerField()),
                ('passiveincome', models.IntegerField()),
                ('current_money', models.IntegerField()),
                ('money_per_click', models.IntegerField()),
                ('click_counter', models.IntegerField()),
            ],
        ),
    ]
