# Generated by Django 4.1.12 on 2023-11-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('username_stat', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('all_time_money', models.IntegerField()),
                ('current_money', models.IntegerField()),
                ('money_perclick', models.IntegerField()),
                ('passive_income', models.IntegerField()),
                ('click_count', models.IntegerField()),
            ],
        ),
    ]
