# Generated by Django 4.1.12 on 2023-11-05 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effect', models.CharField(max_length=255)),
                ('massage', models.CharField(max_length=255)),
                ('Probability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FukudaCustomization',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Head', models.CharField(max_length=255)),
                ('pant', models.CharField(max_length=255)),
                ('torso', models.CharField(max_length=255)),
                ('shoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('powerup_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accuired', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('multiply', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('passive_income', models.IntegerField()),
                ('increase_per_click', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stat',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.skill')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_PowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.powerup')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
