# Generated by Django 4.1.12 on 2023-11-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_powerup_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerup',
            name='skill_name',
            field=models.ForeignKey(default='name', on_delete=django.db.models.deletion.CASCADE, to='auth_app.skill'),
        ),
    ]
