# Generated by Django 4.1.12 on 2023-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_powerup_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_skill',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
