# Generated by Django 4.1.12 on 2023-11-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fukudacustomization',
            name='username',
        ),
        migrations.RemoveField(
            model_name='powerup',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='username',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='user_event',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_powerup',
            name='powerup_name',
        ),
        migrations.RemoveField(
            model_name='user_powerup',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_skill',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='user_skill',
            name='username',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='FukudaCustomization',
        ),
        migrations.DeleteModel(
            name='PowerUp',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='User_Event',
        ),
        migrations.DeleteModel(
            name='User_PowerUp',
        ),
        migrations.DeleteModel(
            name='User_Skill',
        ),
    ]
