# Generated by Django 4.1.12 on 2023-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_skill',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
